# Generated by Django 5.0.2 on 2024-02-28 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campania', models.CharField(max_length=50)),
                ('descripcion_campania', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Periferico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_teclado', models.CharField(max_length=20)),
                ('marca_mouse', models.CharField(max_length=20)),
                ('marca_auricular', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('campania', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Aplicacion_Inventario.campania')),
                ('nombre_persona', models.CharField(max_length=50)),
                ('apellido_persona', models.CharField(max_length=50)),
                ('cuit_persona', models.CharField(max_length=50)),
                ('email_persona', models.EmailField(max_length=254)),
                ('contraseña_preferida_usuario', models.CharField(max_length=10)),
                ('mouse_asignado', models.BooleanField()),
                ('teclado_asignado', models.BooleanField()),
                ('auricular_asignado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Aplicacion_Inventario.persona')),
                ('nombre_notebok', models.CharField(max_length=20)),
                ('marca_notebook', models.CharField(max_length=20)),
                ('numero_serie_notebook', models.CharField(max_length=20)),
                ('modelo_notebook', models.CharField(max_length=20)),
            ],
        ),
    ]
