# Generated by Django 5.0.2 on 2024-02-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion_Inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='campania',
        ),
        migrations.AddField(
            model_name='notebook',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
