# Generated by Django 5.0.2 on 2024-02-29 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion_Inventario', '0002_remove_notebook_persona_remove_persona_campania_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='nombre_notebok',
            new_name='nombre_notebook',
        ),
    ]
