# Generated by Django 5.0.2 on 2024-02-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion_Inventario', '0003_rename_nombre_notebok_notebook_nombre_notebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_computadora', models.CharField(max_length=50)),
            ],
        ),
    ]
