# Generated by Django 5.0.2 on 2024-03-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion_Inventario', '0005_headset_mouse_delete_periferico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='estado_notebook',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
