# Generated by Django 5.0.2 on 2024-03-03 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion_Inventario', '0005_headset_mouse_delete_periferico_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headset',
            options={'ordering': ['marca_headset'], 'verbose_name': 'Headset', 'verbose_name_plural': 'Headsets'},
        ),
        migrations.AlterModelOptions(
            name='mouse',
            options={'ordering': ['marca_mouse'], 'verbose_name': 'Mouse', 'verbose_name_plural': 'Mouses'},
        ),
        migrations.AlterField(
            model_name='campania',
            name='descripcion_campania',
            field=models.CharField(blank='True', default='Sin descripción', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_computadora_escritorio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion_Inventario.computadora'),
        ),
    ]
