# Generated by Django 5.0.2 on 2024-03-03 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion_Inventario', '0006_alter_headset_options_alter_mouse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='id_campania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion_Inventario.campania'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_headset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion_Inventario.headset'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_mouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion_Inventario.mouse'),
        ),
    ]
