# Generated by Django 5.0.2 on 2024-03-02 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion_Inventario', '0006_alter_notebook_estado_notebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='estado_notebook',
        ),
    ]
